### ISSUE TITLE
Windows installer fails to detect OEM PowerPoint release (Win10, PPT2019)

### ISSUE THREAD

**Issue by pburgio** [maxonthegit/PPspliT#1]
Hello, unfortunately, when I try to install the package, I get the following error:

> Failed to automatically detect any Office releases. The add-in has been left unconfigured.

I am running PP2019 on Win10. Feel free to ask if you need more information, or if I can somehow contribute to the project

Paolo

**Comment by maxonthegit** [comment]
Hi,

this might be due to a missed detection by the installer script.
Please start a Command Prompt and report the output of the following command:
```
reg query HKCU\Software\Microsoft\Office\
```
Thank you.

**Comment by pburgio** [comment]
Hello Max,

thanks for the response. Here it is

> HKEY_CURRENT_USER\Software\Microsoft\Office\15.0
> HKEY_CURRENT_USER\Software\Microsoft\Office\16.0
> HKEY_CURRENT_USER\Software\Microsoft\Office\Excel
> HKEY_CURRENT_USER\Software\Microsoft\Office\Outlook
> HKEY_CURRENT_USER\Software\Microsoft\Office\PowerPoint
> HKEY_CURRENT_USER\Software\Microsoft\Office\Teams
> HKEY_CURRENT_USER\Software\Microsoft\Office\Word

Paolo

**Comment by maxonthegit** [comment]
Sorry @pburgio for taking so long to follow up.

I confirm the likelihood that the problem lies in a missed detection of the installed PowerPoint release by the [installer script](https://github.com/maxonthegit/PPspliT/blob/master/src/ppsplit_installer.nsi). The latter iterates over all Office releases mentioned in the system registry at key `HKLM\Software\Microsoft\Office`, both in the 64-bit view and in the 32-bit view, and stops at the first for which a `PowerPoint\InstallRoot` subkey with a valid `Path` value is found: this is considered as an evidence that the corresponding PowerPoint release is truly installed.

I have performed some additional tests to verify that such registry keys are always populated as expected when Office is installed anew, and it actually seems so.
I therefore suggest the following:
* Please also report the output of the following command:
```
reg query HKLM\Software\Microsoft\Office /s /f "InstallRoot" /k /v Path
```
(the last time I have asked you to run a less detailed command pointing to the wrong `HKCU` root key: sorry for that)
I expect a line similar to the following to show up, with release number possibly adjusted according to the PowerPoint version you are using (2019):
```
HKEY_LOCAL_MACHINE\Software\Microsoft\Office\16.0\PowerPoint\InstallRoot
    Path    REG_SZ    C:\Program Files\Microsoft Office\Office16\
```
* If no such output appears, please try again with command:
```
reg query HKLM\Software\Wow6432Node\Microsoft\Office /s /f "InstallRoot" /k /v Path
```

As a last resort, you can of course choose to perform a
## Manual installation
1. Download file [PPspliT.ppam](https://github.com/maxonthegit/PPspliT/raw/master/src/PPT12%2B/PPspliT.ppam) and save it to a path of your choice (`\Users\YOUR_USER_NAME\AppData\Roaming\Microsoft\AddIns` is usually advised as a standard path)
2. Follow the [official instructions from Microsoft](https://support.microsoft.com/en-us/office/add-or-load-a-powerpoint-add-in-3de8bbc2-2481-457a-8841-7334cd5b455f) to configure the add-in inside PowerPoint.

**Comment by pburgio** [comment]
Dear Max,

I managed to have it working by manually saving the .ppam file in the folder you mentioned, and using the installation instructions. Please note that, the file was already present in that folder: probably your installer failed after downloading it

For the rest, I tried to reproduce your steps, as follows:

```
PS C:\WINDOWS\system32> reg query HKLM\Software\Microsoft\Office /s /f "InstallRoot" /k /v Path
                 
End of search: 0 match(es) found.
```

I also tried the expanded syntax:

```
PS C:\WINDOWS\system32> reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office /s /f "InstallRoot" /k /v Path

End of search: 0 match(es) found.
```

Second query:

```
PS C:\WINDOWS\system32> reg query HKLM\Software\Wow6432Node\Microsoft\Office /s /f "InstallRoot" /k /v Path

End of search: 0 match(es) found.
```

Again, expander syntax:

```
PS C:\WINDOWS\system32> reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Office /s /f "InstallRoot" /k /v Path

End of search: 0 match(es) found.
```

Also, note that those keys exist:

```
PS C:\WINDOWS\system32> reg query HKLM\Software\Microsoft\Office\16.0\Common\OEM

HKEY_LOCAL_MACHINE\Software\Microsoft\Office\16.0\Common\OEM
    OOBE    REG_SZ    {92FA0E43-827E-500A-BB60-2A83D8EB80F3}
    OOBEMode    REG_SZ    OEMTA
```

I hope this helps you investigating the problem

As said, right now, I managed to install it: nonetheless, let me know, I am curious to know what was the issue!

Ciao!
Paolo

**Comment by maxonthegit** [comment]
Hi @pburgio.
> I managed to have it working by manually saving the .ppam file in the folder you mentioned, and using the installation instructions. Please note that, the file was already present in that folder: probably the installer failed after downloading it

You are right: indeed the installer copies the required files _before_ attempting to register the add-in.

I have made an additional test: starting from a clean Windows 10 setup, I have freshly installed Office 2019 Professional and immediately checked registry keys without performing any further operations. There is a registered `Path` value for each application-specific key, including `PowerPoint`'s:
```
C:\Users\Max>reg query HKLM\Software\Wow6432Node\Microsoft\Office /s /f "InstallRoot" /k /v Path | findstr "PowerPoint Path"
    Path    REG_SZ    C:\Program Files (x86)\Microsoft Office\root\Office16\
    Path    REG_SZ    C:\Program Files (x86)\Microsoft Office\root\Office16\
    Path    REG_SZ    C:\Program Files (x86)\Microsoft Office\root\Office16\
    Path    REG_SZ    C:\Program Files (x86)\Microsoft Office\root\Office16\
    Path    REG_SZ    C:\Program Files (x86)\Microsoft Office\root\Office16\
HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Office\16.0\PowerPoint\InstallRoot
    Path    REG_SZ    C:\Program Files (x86)\Microsoft Office\root\Office16\
    Path    REG_SZ    C:\Program Files (x86)\Microsoft Office\root\Office16\
    Path    REG_SZ    C:\Program Files (x86)\Microsoft Office\root\Office16\
    Path    REG_SZ    C:\Program Files (x86)\Microsoft Office\root\Office16\
```

This, combined with the additional key you have dumped, induces me to think that you are using an OEM version of Office, possibly coming preinstalled in a factory-supplied machine (maybe by Lenovo?). There is not much I can do to envision these non-standard setups in the installer script.
However, before completely giving up, maybe a dump of the proper registry subtrees could help determine whether there is still a common pattern that could make the installer work also for these OEM versions with little adjustments. If you feel willing to contribute further, please share (as attachments) dumps of the following subtrees:
```
reg query HKLM\Software\Microsoft\Office\16.0 /s
reg query HKLM\Software\Wow6432Node\Microsoft\Office\16.0 /s
```

**Comment by pburgio** [comment]
> However, before completely giving up, maybe a dump of the proper registry subtrees could help determine whether there is still a common pattern that could make the installer work also for these OEM versions with little adjustments. If you feel willing to contribute further, please share (as attachments) dumps of the following subtrees:

Sure! Here it is:

```
PS C:\WINDOWS\system32> reg query HKLM\Software\Microsoft\Office\16.0 /s
HKEY_LOCAL_MACHINE\Software\Microsoft\Office\16.0\Common
HKEY_LOCAL_MACHINE\Software\Microsoft\Office\16.0\Common\OEM
    OOBE    REG_SZ    {92FA0E43-827E-500A-BB60-2A83D8EB80F3}
    OOBEMode    REG_SZ    OEMTA
```
And:

```
PS C:\WINDOWS\system32> reg query HKLM\Software\Wow6432Node\Microsoft\Office\16.0 /s
HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Office\16.0\Common
HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Office\16.0\Common\OEM
    OOBE    REG_SZ    {92FA0E43-827E-500A-BB60-2A83D8EB80F3}
    OOBEMode    REG_SZ    OOBEComplete
```
Let me know if I can provide further help

**Comment by maxonthegit** [comment]
Thank you @pburgio.

Unfortunately, a common pattern that allows for reliable detection of the installed PowerPoint release does not seem to be easy to find in your system. As far as I know, this is required to enable and auto-load PPspliT as a PowerPoint add-in.

Given the apparent peculiarity of your setup, and considering that manual setup is a viable option in such a case, I am closing this as _won't fix_.

**Comment by pburgio** [comment]
Ok, thanks for your help. In any case, we found a workaround (see above) so I'm ok now

Ciao ciao
Paolo
