### ISSUE TITLE
PPspliT 1.27 error: method "copy" of object "TextRange" failed

### ISSUE THREAD

**Issue by dave-doty** [maxonthegit/PPspliT#14]
![image](https://user-images.githubusercontent.com/19274365/208998143-c74f87a9-7b51-4d72-9c74-97877830dff2.png)

This is when I run PPspliT 1.27 (also happens with version 1.24) on this file: https://www.dropbox.com/s/xhuoeb7jyjuienm/example.pptm?dl=0

It's a fairly minimal example, just one slide with two animations that are just fade-ins.

Interestingly, the error goes away if I change the Fade animation to Appear. Then, even if I change back to Fade, the error is still prevented. So I'm not sure what is set in this particular version of the presentation that is causing the error.

**Comment by maxonthegit** [comment]
Hi @dave-doty.

This is a pretty strange issue. Unfortunately, your presentation file does not seem to be available on Dropbox any longer.
In the absence of an example triggering the problem, I can only suggest to upgrade to the recently released PPspliT 2.1 and try again.
But I am not sure at all that this can address your specific issue.

**Comment by dave-doty** [comment]
PPspliT 2.1 fixed the issue. It's also much faster, thanks!
