### ISSUE TITLE
Emphasis effects that change fill colors cause PPspliT to fail when scheme colors are used as target colors

### ISSUE THREAD

**Issue by dave-doty** [maxonthegit/PPspliT#15]
This slide [ch4-slides-planar-coloring.zip](https://github.com/maxonthegit/PPspliT/files/10322095/ch4-slides-planar-coloring.zip) has a sequence of color changes to circles. It causes this error with PPsplit 1.21:

![image](https://user-images.githubusercontent.com/19274365/210011111-a8483727-df93-42c5-8090-3549b2e680e4.png)

**Comment by maxonthegit** [comment]
I confirm this is indeed a bug in PPspliT 2.1: thank you @dave-doty for reporting this.
The issue has been fixed in freshly released PPspliT 2.2, which successfully processes your sample slide deck.
Happy new year!
