### ISSUE TITLE
Animations not splitting on SmartArt

### ISSUE THREAD

**Issue by stevekerrison** [maxonthegit/PPspliT#24]
Hi,

I've been trying to split a PPTX that has smart art animations in them, but for an `n` stage animation I simply get `n` pages will the full smart art on it. Here's the instructions for a MWE:

PowerPoint version: `Microsoft® PowerPoint® for Microsoft 365 MSO (Version 2405 Build 16.0.17628.20006) 64-bit`
PPSpliT version: `2.6`

1. Create a blank slideshow
2. Add a smartart (e.g. a list):  
    ![image](https://github.com/maxonthegit/PPspliT/assets/630182/999dc40f-bf82-48b1-b807-f5f335a319f6)
3. Set animation on smartart (e.g. to "appear") and set to one-by-one in advanced effects  
    ![image](https://github.com/maxonthegit/PPspliT/assets/630182/c165d534-57c5-4bf0-a69b-245c75fb5e10)
4. Run PPSpliT and observe result  
    ![image](https://github.com/maxonthegit/PPspliT/assets/630182/e5cd5c99-76f2-4ab5-b8fd-d0bac0ddd0be)

Is anyone else able to recreate this? Thanks!

**Comment by stevekerrison** [comment]
The obvious workaround for this, at least for content with flat-coloured backgrounds, is to cover the sections of the smart art with a box that is the same colour as the background, then use the "disappear" animation on that, to make the smart art component behind it "appear". This should work regardless of whether PPSpliT can handle SmartArt animation.

**Comment by maxonthegit** [comment]
Thank you very much @stevekerrison for your interest in PPspliT and for taking your time to describe the issue in detail.

As a matter of fact, this is [known limitation #5](https://github.com/maxonthegit/PPspliT/tree/3340c48574d16634d1419861380f74f0f3388758?tab=readme-ov-file#known-limitations), which still applies to the latest relase of PowerPoint for Microsoft 365 at the time of writing this message: certain modifications applied to individual shapes in a composite SmartArt object (e.g., relocation, resizing, visibility, etc.) either cause an error or just fail to work altogether. Unfortunately, so far I couldn't find a way to overcome this issue.

There are indeed a couple of workarounds to address it:
1. One is exactly the one that you have suggested: covering portions of the SmartArt object with additional background-colored shapes which are made to disappear incrementally. This has no really adverse effects (except, maybe, making editing the presentation a little more inconvenient), but is only applicable when a uniformly colored background is in use.
2. Another one is to convert the composite SmartArt object into a shape group, a function that can be accessed by right-clicking on the SmartArt object itself or by following indications in the [related documentation](https://support.microsoft.com/en-us/office/convert-your-smartart-graphic-into-shapes-9512873b-1848-46ec-b269-08f04f36b078#:~:text=Under%20SmartArt%20Tools%2C%20on%20the,to%20open%20the%20Design%20tab.): animations can then be applied to each individual shape. As a main drawback of this approach, editing features of the SmartArt object are irreversibly lost after this transformation.

Sorry, but this is all that I can share concerning this issue, therefore I am proceeding to close it.

**Comment by maxonthegit** [comment]
Closing as indicated.

**Comment by stevekerrison** [comment]
Thanks @maxonthegit. I `ctrl+f`'d the README, but must have searched "smart art" and not "smartart" so didn't see it. My bad.
